
language: node_js

node_js:
  - 8.9.0 # Minimum Requirements
  - 8 # Latest of LTS
  - 9 # Latest of All

cache:
  directories:
    - $HOME/.npm
    - $HOME/.nvm
    - $HOME/.node-gyp
    - $HOME/.node_libraries
    - $HOME/node_modules
    - node_modules

before_script:
  - chmod -R +x sh
